version: "3.8"
services:
  db:
    image: postgres:13.5
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tria_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: